rootProject.name = "PrismaPractice"
include("prismapractice-api")
include("prismapractice-command")
include("prismapractice-config")
include("prismapractice-core")
include("prismapractice-data")
include("prismapractice-feedback")
include("prismapractice-paper-feedback")
include("prismapractice-paper-ui")
include("prismapractice-paper-scoreboard")
include("prismapractice-proxy")
include("prismapractice-hub")
include("prismapractice-match")
include("prismapractice-ffa")
