name: PrismaPracticeHub
version: ${version}
main: com.stephanofer.prismapractice.hub.PrismaPracticeHubPlugin
description: PrismaPractice hub plugin
author: Stephanofer
api-version: '1.21.8'
softdepend: [zMenu]
libraries:
  - io.lettuce:lettuce-core:${lettuceVersion}
permissions:
  prismapractice.admin.reload:
    description: Allows operational runtime reloads
    default: op
