name: PrismaPracticeMatch
version: ${version}
main: com.stephanofer.prismapractice.match.PrismaPracticeMatchPlugin
description: PrismaPractice match plugin
author: Stephanofer
api-version: '1.21.8'
libraries:
  - io.lettuce:lettuce-core:${lettuceVersion}
permissions:
  prismapractice.admin.reload:
    description: Allows operational runtime reloads
    default: op
