CREATE TABLE IF NOT EXISTS practice_matches (
    match_id CHAR(36) NOT NULL PRIMARY KEY,
    queue_id VARCHAR(64) NOT NULL,
    mode_id VARCHAR(64) NOT NULL,
    player_type VARCHAR(32) NOT NULL,
    queue_type VARCHAR(16) NOT NULL,
    matchmaking_profile VARCHAR(32) NOT NULL,
    left_player_id CHAR(36) NOT NULL,
    right_player_id CHAR(36) NOT NULL,
    arena_id VARCHAR(64) NOT NULL,
    arena_type VARCHAR(16) NOT NULL,
    region_id VARCHAR(32) NOT NULL,
    runtime_type VARCHAR(16) NOT NULL,
    runtime_server_id VARCHAR(64) NOT NULL,
    rounds_to_win INT NOT NULL,
    pre_fight_delay_seconds INT NOT NULL,
    max_duration_seconds INT NOT NULL,
    kit_reference VARCHAR(128) NOT NULL,
    rules_csv TEXT NOT NULL,
    spectator_allowed BOOLEAN NOT NULL,
    series_format VARCHAR(32) NOT NULL,
    left_rounds_won INT NOT NULL,
    right_rounds_won INT NOT NULL,
    current_round INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    winner_player_id CHAR(36) NULL,
    loser_player_id CHAR(36) NULL,
    result_type VARCHAR(32) NULL,
    cancel_reason VARCHAR(255) NOT NULL,
    failure_reason VARCHAR(255) NOT NULL,
    recoverable BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP NULL,
    ended_at TIMESTAMP NULL,
    KEY idx_practice_matches_queue_id (queue_id),
    KEY idx_practice_matches_players (left_player_id, right_player_id),
    KEY idx_practice_matches_status (status)
);
